import os

def create_files():
    files = {
        "backend/app/agents/core/state.py": "from pydantic import BaseModel, Field\nfrom typing import Optional, List, Dict, Any\n\nclass SharedContext(BaseModel):\n    original_target: str\n    scan_type: str # URL or QR\n    normalized_url: Optional[str] = None\n    \n    # Security Findings\n    ssl_valid: Optional[bool] = None\n    whois_age_days: Optional[int] = None\n    threat_intel_flags: List[str] = Field(default_factory=list)\n    \n    # Brand Verification\n    impersonated_brand: Optional[str] = None\n    official_url: Optional[str] = None\n    \n    # Risk Assessment\n    risk_score: Optional[float] = None\n    risk_level: Optional[str] = None\n    confidence: Optional[float] = None\n    \n    # Output Generation\n    explanations: List[str] = Field(default_factory=list)\n    recommendations: List[str] = Field(default_factory=list)\n    cyber_tip: Optional[str] = None\n    \n    raw_report: Optional[str] = None\n",
        "backend/app/agents/core/base.py": "import asyncio\nfrom abc import ABC, abstractmethod\nfrom .state import SharedContext\nimport logging\n\nlogger = logging.getLogger(__name__)\n\nclass AgentBase(ABC):\n    def __init__(self, name: str):\n        self.name = name\n        self.max_retries = 3\n\n    @property\n    @abstractmethod\n    def prompt(self) -> str:\n        pass\n\n    @abstractmethod\n    async def execute(self, context: SharedContext) -> SharedContext:\n        pass\n        \n    async def run(self, context: SharedContext) -> SharedContext:\n        for attempt in range(self.max_retries):\n            try:\n                logger.info(f\"[{self.name}] Executing attempt {attempt + 1}\")\n                # Simulating LLM execution latency\n                await asyncio.sleep(0.5)\n                new_context = await self.execute(context)\n                logger.info(f\"[{self.name}] Completed successfully\")\n                return new_context\n            except Exception as e:\n                logger.error(f\"[{self.name}] Error: {e}\")\n                if attempt == self.max_retries - 1:\n                    raise e\n                await asyncio.sleep(1)\n        return context\n",
        "backend/app/agents/core/orchestrator.py": "from .state import SharedContext\nimport asyncio\nimport logging\n\nlogger = logging.getLogger(__name__)\n\nclass DAGOrchestrator:\n    def __init__(self, agents_map: dict):\n        # agents_map: {\"phase1\": [Agent1], \"phase2\": [Agent2, Agent3], ...}\n        self.agents_map = agents_map\n\n    async def run(self, initial_context: SharedContext) -> SharedContext:\n        context = initial_context\n        \n        for phase, agents in self.agents_map.items():\n            logger.info(f\"--- Starting {phase} ---\")\n            # Run agents in the current phase concurrently\n            tasks = [agent.run(context.model_copy(deep=True)) for agent in agents]\n            results = await asyncio.gather(*tasks, return_exceptions=True)\n            \n            # Merge state\n            for result in results:\n                if isinstance(result, Exception):\n                    logger.error(f\"Agent failed: {result}\")\n                else:\n                    # For a real implementation, write a deep merge. Here we do simple overwrite for non-nulls.\n                    for key, val in result.model_dump().items():\n                        if val is not None and (not isinstance(val, list) or len(val) > 0):\n                            setattr(context, key, val)\n                            \n        logger.info(\"--- Orchestration Complete ---\")\n        return context\n"
    }

    for path, content in files.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

if __name__ == "__main__":
    create_files()
    print("Backend Stage 7 Core Framework scaffolded.")
