import os

def create_files():
    files = {
        "backend/app/models/user.py": "from sqlalchemy import Column, Integer, String, Boolean\nfrom app.database.session import Base\n\nclass User(Base):\n    __tablename__ = 'users'\n    id = Column(Integer, primary_key=True, index=True)\n    email = Column(String, unique=True, index=True, nullable=False)\n    hashed_password = Column(String, nullable=False)\n    is_active = Column(Boolean, default=True)\n",
        "backend/app/models/scan.py": "from sqlalchemy import Column, Integer, String, DateTime, Float, ForeignKey\nfrom sqlalchemy.sql import func\nfrom sqlalchemy.orm import relationship\nfrom app.database.session import Base\n\nclass Scan(Base):\n    __tablename__ = 'scans'\n    id = Column(Integer, primary_key=True, index=True)\n    user_id = Column(Integer, ForeignKey('users.id'), nullable=True)\n    target_url = Column(String, nullable=False)\n    status = Column(String, default='pending')\n    risk_score = Column(Float, nullable=True)\n    created_at = Column(DateTime(timezone=True), server_default=func.now())\n",
        "backend/app/models/__init__.py": "from app.models.user import User\nfrom app.models.scan import Scan\n",
        "backend/app/schemas/user.py": "from pydantic import BaseModel, EmailStr\n\nclass UserCreate(BaseModel):\n    email: EmailStr\n    password: str\n\nclass UserResponse(BaseModel):\n    id: int\n    email: EmailStr\n    is_active: bool\n    class Config:\n        orm_mode = True\n",
        "backend/app/schemas/scan.py": "from pydantic import BaseModel\nfrom typing import Optional\nfrom datetime import datetime\n\nclass ScanCreate(BaseModel):\n    target_url: str\n\nclass ScanResponse(BaseModel):\n    id: int\n    target_url: str\n    status: str\n    risk_score: Optional[float]\n    created_at: datetime\n    class Config:\n        orm_mode = True\n",
        "backend/app/services/auth.py": "from passlib.context import CryptContext\nfrom jose import jwt\nfrom datetime import datetime, timedelta\nfrom app.config.settings import settings\n\npwd_context = CryptContext(schemes=[\"bcrypt\"], deprecated=\"auto\")\n\ndef verify_password(plain_password, hashed_password):\n    return pwd_context.verify(plain_password, hashed_password)\n\ndef get_password_hash(password):\n    return pwd_context.hash(password)\n\ndef create_access_token(data: dict):\n    to_encode = data.copy()\n    expire = datetime.utcnow() + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)\n    to_encode.update({\"exp\": expire})\n    return jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)\n",
        "backend/app/api/auth.py": "from fastapi import APIRouter, Depends, HTTPException\nfrom sqlalchemy.ext.asyncio import AsyncSession\nfrom sqlalchemy.future import select\nfrom app.database.session import get_db\nfrom app.models.user import User\nfrom app.schemas.user import UserCreate, UserResponse\nfrom app.services.auth import get_password_hash, verify_password, create_access_token\nfrom pydantic import BaseModel\n\nrouter = APIRouter()\n\nclass Token(BaseModel):\n    access_token: str\n    token_type: str\n\n@router.post(\"/register\", response_model=UserResponse)\nasync def register(user: UserCreate, db: AsyncSession = Depends(get_db)):\n    result = await db.execute(select(User).where(User.email == user.email))\n    db_user = result.scalars().first()\n    if db_user:\n        raise HTTPException(status_code=400, detail=\"Email already registered\")\n    hashed_password = get_password_hash(user.password)\n    new_user = User(email=user.email, hashed_password=hashed_password)\n    db.add(new_user)\n    await db.commit()\n    await db.refresh(new_user)\n    return new_user\n\n@router.post(\"/login\", response_model=Token)\nasync def login(user: UserCreate, db: AsyncSession = Depends(get_db)):\n    result = await db.execute(select(User).where(User.email == user.email))\n    db_user = result.scalars().first()\n    if not db_user or not verify_password(user.password, db_user.hashed_password):\n        raise HTTPException(status_code=400, detail=\"Incorrect email or password\")\n    access_token = create_access_token(data={\"sub\": db_user.email})\n    return {\"access_token\": access_token, \"token_type\": \"bearer\"}\n",
        "backend/app/api/scans.py": "from fastapi import APIRouter, Depends\nfrom sqlalchemy.ext.asyncio import AsyncSession\nfrom app.database.session import get_db\nfrom app.schemas.scan import ScanCreate, ScanResponse\nfrom app.models.scan import Scan\n\nrouter = APIRouter()\n\n@router.post(\"/\", response_model=ScanResponse)\nasync def create_scan(scan_in: ScanCreate, db: AsyncSession = Depends(get_db)):\n    scan = Scan(target_url=scan_in.target_url)\n    db.add(scan)\n    await db.commit()\n    await db.refresh(scan)\n    # Here we would trigger the Antigravity Workflow\n    return scan\n",
        "backend/app/main.py": "from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\nfrom app.api.auth import router as auth_router\nfrom app.api.scans import router as scans_router\nfrom app.database.session import engine, Base\n\napp = FastAPI(title=\"TrustGuardAI\", description=\"Multi-Agent Architecture Backend\")\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=[\"*\"],\n    allow_credentials=True,\n    allow_methods=[\"*\"],\n    allow_headers=[\"*\"],\n)\n\n@app.on_event(\"startup\")\nasync def startup():\n    async with engine.begin() as conn:\n        await conn.run_sync(Base.metadata.create_all)\n\napp.include_router(auth_router, prefix=\"/auth\", tags=[\"auth\"])\napp.include_router(scans_router, prefix=\"/scans\", tags=[\"scans\"])\n\n@app.get(\"/health\")\nasync def health():\n    return {\"status\": \"ok\"}\n"
    }
    for path, content in files.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

if __name__ == "__main__":
    create_files()
    print("Backend Phase 1 scaffolded.")
