import os

def create_files():
    files = {
        "backend/alembic.ini": "[alembic]\nscript_location = alembic\nprepend_sys_path = .\nversion_path_separator = os\nsqlalchemy.url = postgresql+asyncpg://postgres:postgres@db:5432/trustguard\n\n[post_write_hooks]\n\n[loggers]\nkeys = root,sqlalchemy,alembic\n\n[handlers]\nkeys = console\n\n[formatters]\nkeys = generic\n\n[logger_root]\nlevel = WARN\nhandlers = console\nqualname =\n\n[logger_sqlalchemy]\nlevel = WARN\nhandlers =\nqualname = sqlalchemy.engine\n\n[logger_alembic]\nlevel = INFO\nhandlers =\nqualname = alembic\n\n[handler_console]\nclass = StreamHandler\nargs = (sys.stderr,)\nlevel = NOTSET\nformatter = generic\n\n[formatter_generic]\nformat = %(levelname)-5.5s [%(name)s] %(message)s\ndatefmt = %H:%M:%S\n",
        "backend/alembic/env.py": "import asyncio\nfrom logging.config import fileConfig\nfrom sqlalchemy import pool\nfrom sqlalchemy.engine import Connection\nfrom sqlalchemy.ext.asyncio import async_engine_from_config\nfrom alembic import context\nfrom app.models.base import Base\nimport app.models\nfrom app.config.settings import settings\n\nconfig = context.config\nif config.config_file_name is not None:\n    fileConfig(config.config_file_name)\n\ntarget_metadata = Base.metadata\nconfig.set_main_option(\"sqlalchemy.url\", settings.DATABASE_URL)\n\ndef run_migrations_offline() -> None:\n    url = config.get_main_option(\"sqlalchemy.url\")\n    context.configure(\n        url=url,\n        target_metadata=target_metadata,\n        literal_binds=True,\n        dialect_opts={\"paramstyle\": \"named\"},\n    )\n    with context.begin_transaction():\n        context.run_migrations()\n\ndef do_run_migrations(connection: Connection) -> None:\n    context.configure(connection=connection, target_metadata=target_metadata)\n    with context.begin_transaction():\n        context.run_migrations()\n\nasync def run_async_migrations() -> None:\n    connectable = async_engine_from_config(\n        config.get_section(config.config_ini_section, {}),\n        prefix=\"sqlalchemy.\",\n        poolclass=pool.NullPool,\n    )\n    async with connectable.connect() as connection:\n        await connection.run_sync(do_run_migrations)\n    await connectable.dispose()\n\ndef run_migrations_online() -> None:\n    asyncio.run(run_async_migrations())\n\nif context.is_offline_mode():\n    run_migrations_offline()\nelse:\n    run_migrations_online()\n",
        "backend/alembic/script.py.mako": "/* Mako template for alembic script */\n\"\"\"${message}\n\nRevision ID: ${up_revision}\nRevises: ${down_revision | comma,n}\nCreate Date: ${create_date}\n\n\"\"\"\nfrom typing import Sequence, Union\nfrom alembic import op\nimport sqlalchemy as sa\n${imports if imports else \"\"}\n\n# revision identifiers, used by Alembic.\nrevision: str = ${repr(up_revision)}\ndown_revision: Union[str, None] = ${repr(down_revision)}\nbranch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}\ndepends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}\n\ndef upgrade() -> None:\n    ${upgrades if upgrades else \"pass\"}\n\ndef downgrade() -> None:\n    ${downgrades if downgrades else \"pass\"}\n",
        "backend/app/repositories/scan_repo.py": "from sqlalchemy.ext.asyncio import AsyncSession\nfrom sqlalchemy.future import select\nfrom app.models.scan import Scan\nfrom app.models.embedding import Embedding\nfrom .base import BaseRepository\nfrom typing import List\nimport logging\n\nlogger = logging.getLogger(__name__)\n\nclass ScanRepository(BaseRepository[Scan]):\n    def __init__(self):\n        super().__init__(Scan)\n        \n    async def get_history_by_user(self, db: AsyncSession, user_id: int) -> List[Scan]:\n        result = await db.execute(select(self.model).filter(self.model.user_id == user_id).order_by(self.model.created_at.desc()))\n        return result.scalars().all()\n\n    async def find_similar_threats(self, db: AsyncSession, vector: list[float], limit: int = 5) -> List[Scan]:\n        # Using pgvector cosine distance `<=>` operator\n        # Embedding.vector <=> vector\n        try:\n            stmt = select(Scan).join(Embedding).order_by(Embedding.vector.cosine_distance(vector)).limit(limit)\n            result = await db.execute(stmt)\n            return result.scalars().all()\n        except Exception as e:\n            logger.error(f\"Failed pgvector similarity search: {e}\")\n            return []\n\nscan_repo = ScanRepository()\n",
        "backend/scripts/seed_db.py": "import asyncio\nfrom sqlalchemy.ext.asyncio import AsyncSession\nfrom app.database.session import AsyncSessionLocal, engine\nfrom app.models.base import Base\nfrom app.models.user import User\nfrom app.models.scan import Scan\nfrom app.models.cybertip import CyberTip\nfrom app.security.hashing import get_password_hash\n\nasync def seed():\n    print(\"Initializing database tables...\")\n    async with engine.begin() as conn:\n        await conn.run_sync(Base.metadata.create_all)\n        # create pgvector extension if not exists\n        await conn.execute(\"CREATE EXTENSION IF NOT EXISTS vector;\")\n\n    async with AsyncSessionLocal() as session:\n        print(\"Seeding Users...\")\n        admin = User(email=\"admin@trustguard.ai\", hashed_password=get_password_hash(\"admin123\"), role=\"admin\")\n        session.add(admin)\n        \n        print(\"Seeding CyberTips...\")\n        tip = CyberTip(title=\"Phishing Awareness\", content=\"Always check the sender domain in unexpected emails.\", category=\"Phishing\")\n        session.add(tip)\n        \n        print(\"Seeding Mock Scan...\")\n        scan = Scan(target=\"https://fake-login.com\", scan_type=\"URL\", status=\"completed\", risk_score=95.0, risk_level=\"Critical\", user=admin)\n        session.add(scan)\n        \n        await session.commit()\n        print(\"Database seeded successfully.\")\n\nif __name__ == \"__main__\":\n    asyncio.run(seed())\n"
    }

    for path, content in files.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

if __name__ == "__main__":
    create_files()
    print("Backend Phase 8 (Part 2) scaffolded.")
