import os

def create_files():
    files = {
        "mcp/server.py": "from fastapi import FastAPI, HTTPException, Request\nfrom pydantic import BaseModel\nfrom tools.whois_tool import get_whois\nfrom tools.ssl_tool import get_ssl\nfrom tools.threat_tool import get_threat_intel\nimport os\n\napp = FastAPI(title=\"TrustGuardAI MCP Server\")\n\nclass ToolRequest(BaseModel):\n    tool: str\n    target: str\n\n@app.middleware(\"http\")\nasync def verify_api_key(request: Request, call_next):\n    key = request.headers.get(\"X-MCP-API-KEY\")\n    if key != os.getenv(\"MCP_API_KEY\", \"mcp_secret\") and request.url.path != \"/health\":\n        return HTTPException(status_code=403, detail=\"Forbidden\")\n    response = await call_next(request)\n    return response\n\n@app.get(\"/health\")\ndef health(): return {\"status\": \"ok\"}\n\n@app.post(\"/execute\")\nasync def execute_tool(req: ToolRequest):\n    try:\n        if req.tool == \"whois\":\n            data = get_whois(req.target)\n        elif req.tool == \"ssl\":\n            data = get_ssl(req.target)\n        elif req.tool == \"threat\":\n            data = get_threat_intel(req.target)\n        else:\n            raise HTTPException(status_code=404, detail=\"Tool not found\")\n        return {\"status\": \"success\", \"data\": data}\n    except Exception as e:\n        return {\"status\": \"error\", \"detail\": str(e)}\n",
        "mcp/tools/whois_tool.py": "def get_whois(domain: str):\n    return {\"domain\": domain, \"age_days\": 15, \"registrar\": \"MockRegistrar\", \"risk\": \"high\"}\n",
        "mcp/tools/ssl_tool.py": "def get_ssl(domain: str):\n    return {\"valid\": True, \"issuer\": \"Let's Encrypt\", \"expires_in_days\": 45}\n",
        "mcp/tools/threat_tool.py": "def get_threat_intel(domain: str):\n    return {\"listed_in_phishing_db\": True, \"malware_reports\": 2}\n",
        "backend/app/agents/base.py": "import os\nfrom pydantic import BaseModel\nimport httpx\n\nclass AgentResponse(BaseModel):\n    agent_name: str\n    status: str\n    finding: dict\n    risk_score: float\n\nasync def call_mcp_tool(tool_name: str, target: str):\n    mcp_url = os.getenv(\"MCP_URL\", \"http://localhost:8001/execute\")\n    api_key = os.getenv(\"MCP_API_KEY\", \"mcp_secret\")\n    async with httpx.AsyncClient() as client:\n        resp = await client.post(mcp_url, json={\"tool\": tool_name, \"target\": target}, headers={\"X-MCP-API-KEY\": api_key})\n        return resp.json().get(\"data\", {})\n",
        "backend/app/agents/whois_agent.py": "from app.agents.base import call_mcp_tool, AgentResponse\nimport asyncio\n\nasync def analyze_whois(target: str) -> AgentResponse:\n    await asyncio.sleep(1) # simulate LLM thinking\n    data = await call_mcp_tool(\"whois\", target)\n    risk = 0.8 if data.get(\"age_days\", 100) < 30 else 0.1\n    return AgentResponse(agent_name=\"WHOIS Analysis Agent\", status=\"completed\", finding=data, risk_score=risk)\n",
        "backend/app/agents/ssl_agent.py": "from app.agents.base import call_mcp_tool, AgentResponse\nimport asyncio\n\nasync def analyze_ssl(target: str) -> AgentResponse:\n    await asyncio.sleep(1.2)\n    data = await call_mcp_tool(\"ssl\", target)\n    risk = 0.0 if data.get(\"valid\") else 1.0\n    return AgentResponse(agent_name=\"SSL Analysis Agent\", status=\"completed\", finding=data, risk_score=risk)\n",
        "backend/app/agents/threat_agent.py": "from app.agents.base import call_mcp_tool, AgentResponse\nimport asyncio\n\nasync def analyze_threat(target: str) -> AgentResponse:\n    await asyncio.sleep(1.5)\n    data = await call_mcp_tool(\"threat\", target)\n    risk = 0.9 if data.get(\"listed_in_phishing_db\") else 0.0\n    return AgentResponse(agent_name=\"Threat Intel Agent\", status=\"completed\", finding=data, risk_score=risk)\n",
        "backend/app/workflows/engine.py": "import asyncio\nimport json\nfrom app.agents.whois_agent import analyze_whois\nfrom app.agents.ssl_agent import analyze_ssl\nfrom app.agents.threat_agent import analyze_threat\n\nasync def antigravity_scan_workflow(target_url: str):\n    yield f\"data: {{'status': 'starting', 'target': '{target_url}'}}\\n\\n\"\n    await asyncio.sleep(0.5)\n    \n    tasks = [\n        analyze_whois(target_url),\n        analyze_ssl(target_url),\n        analyze_threat(target_url)\n    ]\n    \n    for task in asyncio.as_completed(tasks):\n        result = await task\n        res_json = result.json()\n        yield f\"data: {res_json}\\n\\n\"\n        \n    yield f\"data: {{'status': 'completed', 'final_risk_score': 0.85}}\\n\\n\"\n",
        "backend/app/api/scans.py": "from fastapi import APIRouter, Depends\nfrom fastapi.responses import StreamingResponse\nfrom app.schemas.scan import ScanCreate\nfrom app.workflows.engine import antigravity_scan_workflow\n\nrouter = APIRouter()\n\n@router.post(\"/stream\")\nasync def stream_scan(scan_in: ScanCreate):\n    return StreamingResponse(\n        antigravity_scan_workflow(scan_in.target_url),\n        media_type=\"text/event-stream\"\n    )\n"
    }

    for path, content in files.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

if __name__ == "__main__":
    create_files()
    print("Backend Phases 2, 3, 4 scaffolded.")
