import os

def create_files():
    files = {
        "backend/app/repositories/base.py": "from sqlalchemy.ext.asyncio import AsyncSession\nfrom sqlalchemy.future import select\nfrom typing import Generic, TypeVar, Type\nfrom app.models.base import BaseModel\n\nModelType = TypeVar(\"ModelType\", bound=BaseModel)\n\nclass BaseRepository(Generic[ModelType]):\n    def __init__(self, model: Type[ModelType]):\n        self.model = model\n\n    async def get(self, db: AsyncSession, id: int) -> ModelType | None:\n        result = await db.execute(select(self.model).filter(self.model.id == id))\n        return result.scalars().first()\n\n    async def create(self, db: AsyncSession, obj_in: dict) -> ModelType:\n        obj_data = self.model(**obj_in)\n        db.add(obj_data)\n        await db.commit()\n        await db.refresh(obj_data)\n        return obj_data\n",
        "backend/app/repositories/user_repo.py": "from sqlalchemy.ext.asyncio import AsyncSession\nfrom sqlalchemy.future import select\nfrom app.models.user import User\nfrom .base import BaseRepository\n\nclass UserRepository(BaseRepository[User]):\n    def __init__(self):\n        super().__init__(User)\n        \n    async def get_by_email(self, db: AsyncSession, email: str) -> User | None:\n        result = await db.execute(select(self.model).filter(self.model.email == email))\n        return result.scalars().first()\n\nuser_repo = UserRepository()\n",
        "backend/app/services/auth_service.py": "from sqlalchemy.ext.asyncio import AsyncSession\nfrom app.repositories.user_repo import user_repo\nfrom app.schemas.user import UserCreate, UserLogin\nfrom app.security.hashing import get_password_hash, verify_password\nfrom app.security.jwt import create_access_token\nfrom app.exceptions.custom import DomainException, UnauthorizedException\n\nclass AuthService:\n    @staticmethod\n    async def register(db: AsyncSession, user_in: UserCreate):\n        existing = await user_repo.get_by_email(db, user_in.email)\n        if existing:\n            raise DomainException(\"Email already registered\", 400, \"EMAIL_EXISTS\")\n        hashed = get_password_hash(user_in.password)\n        return await user_repo.create(db, {\"email\": user_in.email, \"hashed_password\": hashed})\n\n    @staticmethod\n    async def login(db: AsyncSession, user_in: UserLogin):\n        user = await user_repo.get_by_email(db, user_in.email)\n        if not user or not verify_password(user_in.password, user.hashed_password):\n            raise UnauthorizedException(\"Incorrect email or password\")\n        return {\"access_token\": create_access_token({\"sub\": user.email}), \"token_type\": \"bearer\"}\n",
        "backend/app/services/scan_service.py": "from sqlalchemy.ext.asyncio import AsyncSession\nfrom app.schemas.scan import URLScanRequest, QRScanRequest\n\nclass ScanService:\n    @staticmethod\n    async def process_url_scan(db: AsyncSession, scan_req: URLScanRequest):\n        # AI logic will be plugged in here later via Google ADK\n        # Returning mock structured JSON per specification\n        return {\n            \"id\": 1,\n            \"target\": str(scan_req.target_url),\n            \"scan_type\": \"URL\",\n            \"status\": \"completed\",\n            \"risk_score\": 95.0,\n            \"created_at\": \"2026-07-07T12:00:00Z\"\n        }\n\n    @staticmethod\n    async def process_qr_scan(db: AsyncSession, scan_req: QRScanRequest):\n        return {\n            \"id\": 2,\n            \"target\": \"QR_PAYLOAD\",\n            \"scan_type\": \"QR\",\n            \"status\": \"completed\",\n            \"risk_score\": 10.0,\n            \"created_at\": \"2026-07-07T12:05:00Z\"\n        }\n",
        "backend/app/controllers/auth_controller.py": "from fastapi import APIRouter, Depends\nfrom sqlalchemy.ext.asyncio import AsyncSession\nfrom app.database.session import get_db\nfrom app.schemas.user import UserCreate, UserLogin, UserResponse\nfrom app.services.auth_service import AuthService\n\nrouter = APIRouter()\n\n@router.post(\"/register\", response_model=UserResponse)\nasync def register(user_in: UserCreate, db: AsyncSession = Depends(get_db)):\n    return await AuthService.register(db, user_in)\n\n@router.post(\"/login\")\nasync def login(user_in: UserLogin, db: AsyncSession = Depends(get_db)):\n    return await AuthService.login(db, user_in)\n",
        "backend/app/controllers/scan_controller.py": "from fastapi import APIRouter, Depends\nfrom sqlalchemy.ext.asyncio import AsyncSession\nfrom app.database.session import get_db\nfrom app.schemas.scan import URLScanRequest, QRScanRequest, ScanResponse\nfrom app.services.scan_service import ScanService\n\nrouter = APIRouter()\n\n@router.post(\"/url\", response_model=ScanResponse)\nasync def scan_url(scan_in: URLScanRequest, db: AsyncSession = Depends(get_db)):\n    return await ScanService.process_url_scan(db, scan_in)\n\n@router.post(\"/qr\", response_model=ScanResponse)\nasync def scan_qr(scan_in: QRScanRequest, db: AsyncSession = Depends(get_db)):\n    return await ScanService.process_qr_scan(db, scan_in)\n",
        "backend/app/controllers/user_controller.py": "from fastapi import APIRouter\n\nrouter = APIRouter()\n\n@router.get(\"/profile\")\nasync def get_profile():\n    return {\"email\": \"admin@trustguard.ai\", \"role\": \"admin\", \"is_active\": True}\n\n@router.get(\"/settings\")\nasync def get_settings():\n    return {\"theme\": \"dark\", \"notifications_enabled\": True, \"aggressive_scan\": False}\n\n@router.get(\"/history\")\nasync def get_history():\n    return [{\"id\": 1, \"target\": \"https://example.com\", \"risk_score\": 2.0}]\n\n@router.get(\"/report\")\nasync def get_report():\n    return {\"status\": \"generated\", \"url\": \"/downloads/report_1.pdf\"}\n",
        "backend/app/routes/api.py": "from fastapi import APIRouter\nfrom app.controllers.auth_controller import router as auth_router\nfrom app.controllers.scan_controller import router as scan_router\nfrom app.controllers.user_controller import router as user_router\n\napi_router = APIRouter()\napi_router.include_router(auth_router, prefix=\"\", tags=[\"auth\"])\napi_router.include_router(scan_router, prefix=\"/scan\", tags=[\"scan\"])\napi_router.include_router(user_router, prefix=\"\", tags=[\"user\"])\n",
        "backend/app/main.py": "from fastapi import FastAPI\nfrom fastapi.responses import JSONResponse\nfrom app.config.settings import settings\nfrom app.routes.api import api_router\nfrom app.exceptions.custom import DomainException\nfrom app.exceptions.handlers import domain_exception_handler, general_exception_handler\nfrom app.middleware.security import SecurityHeadersMiddleware\nfrom app.middleware.rate_limit import RateLimitMiddleware\n\napp = FastAPI(\n    title=settings.PROJECT_NAME,\n    version=settings.VERSION,\n    openapi_url=f\"{settings.API_V1_STR}/openapi.json\"\n)\n\n# Middleware\napp.add_middleware(SecurityHeadersMiddleware)\napp.add_middleware(RateLimitMiddleware)\n\n# Exception Handlers\napp.add_exception_handler(DomainException, domain_exception_handler)\napp.add_exception_handler(Exception, general_exception_handler)\n\n# Routes\napp.include_router(api_router, prefix=settings.API_V1_STR)\n\n@app.get(\"/health\", tags=[\"system\"])\nasync def health_check():\n    return {\"status\": \"healthy\"}\n\n@app.get(\"/version\", tags=[\"system\"])\nasync def get_version():\n    return {\"version\": settings.VERSION}\n"
    }

    for path, content in files.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

if __name__ == "__main__":
    create_files()
    print("Backend Phase 7 (Part 2) scaffolded.")
