import os

def create_files():
    files = {
        "backend/app/models/base.py": "from sqlalchemy import Column, Integer, DateTime\nfrom sqlalchemy.sql import func\nfrom sqlalchemy.orm import declarative_base\n\nBase = declarative_base()\n\nclass BaseModel(Base):\n    __abstract__ = True\n    id = Column(Integer, primary_key=True, index=True)\n    created_at = Column(DateTime(timezone=True), server_default=func.now())\n    updated_at = Column(DateTime(timezone=True), onupdate=func.now())\n",
        "backend/app/models/user.py": "from sqlalchemy import Column, String, Boolean\nfrom sqlalchemy.orm import relationship\nfrom .base import BaseModel\n\nclass User(BaseModel):\n    __tablename__ = 'users'\n    email = Column(String, unique=True, index=True, nullable=False)\n    hashed_password = Column(String, nullable=False)\n    is_active = Column(Boolean, default=True)\n    role = Column(String, default=\"user\")\n    scans = relationship(\"Scan\", back_populates=\"user\", cascade=\"all, delete-orphan\")\n    audit_logs = relationship(\"AuditLog\", back_populates=\"user\", cascade=\"all, delete-orphan\")\n",
        "backend/app/models/scan.py": "from sqlalchemy import Column, Integer, String, Float, ForeignKey\nfrom sqlalchemy.orm import relationship\nfrom .base import BaseModel\n\nclass Scan(BaseModel):\n    __tablename__ = 'scans'\n    user_id = Column(Integer, ForeignKey('users.id'), nullable=True)\n    target = Column(String, nullable=False)\n    scan_type = Column(String, nullable=False) # 'URL' or 'QR'\n    status = Column(String, default='pending')\n    risk_score = Column(Float, nullable=True)\n    risk_level = Column(String, nullable=True)\n    confidence_score = Column(Float, nullable=True)\n    \n    user = relationship(\"User\", back_populates=\"scans\")\n    threat_results = relationship(\"ThreatResult\", back_populates=\"scan\", cascade=\"all, delete-orphan\")\n    recommendations = relationship(\"Recommendation\", back_populates=\"scan\", cascade=\"all, delete-orphan\")\n    official_websites = relationship(\"OfficialWebsite\", back_populates=\"scan\", cascade=\"all, delete-orphan\")\n    threat_sources = relationship(\"ThreatSource\", back_populates=\"scan\", cascade=\"all, delete-orphan\")\n    embedding = relationship(\"Embedding\", back_populates=\"scan\", uselist=False, cascade=\"all, delete-orphan\")\n    report = relationship(\"Report\", back_populates=\"scan\", uselist=False, cascade=\"all, delete-orphan\")\n",
        "backend/app/models/details.py": "from sqlalchemy import Column, Integer, String, Boolean, ForeignKey\nfrom sqlalchemy.orm import relationship\nfrom .base import BaseModel\n\nclass ThreatResult(BaseModel):\n    __tablename__ = 'threat_results'\n    scan_id = Column(Integer, ForeignKey('scans.id'), nullable=False)\n    agent_name = Column(String, nullable=False)\n    status = Column(String, nullable=False) # Fail/Warn/Pass\n    description = Column(String, nullable=False)\n    passed = Column(Boolean, nullable=False)\n    scan = relationship(\"Scan\", back_populates=\"threat_results\")\n\nclass Recommendation(BaseModel):\n    __tablename__ = 'recommendations'\n    scan_id = Column(Integer, ForeignKey('scans.id'), nullable=False)\n    text = Column(String, nullable=False)\n    priority = Column(String, nullable=False)\n    scan = relationship(\"Scan\", back_populates=\"recommendations\")\n\nclass OfficialWebsite(BaseModel):\n    __tablename__ = 'official_websites'\n    scan_id = Column(Integer, ForeignKey('scans.id'), nullable=False)\n    brand_name = Column(String, nullable=False)\n    official_url = Column(String, nullable=False)\n    scan = relationship(\"Scan\", back_populates=\"official_websites\")\n\nclass ThreatSource(BaseModel):\n    __tablename__ = 'threat_sources'\n    scan_id = Column(Integer, ForeignKey('scans.id'), nullable=False)\n    source_name = Column(String, nullable=False)\n    reference_url = Column(String, nullable=True)\n    scan = relationship(\"Scan\", back_populates=\"threat_sources\")\n",
        "backend/app/models/report.py": "from sqlalchemy import Column, Integer, String, ForeignKey\nfrom sqlalchemy.orm import relationship\nfrom .base import BaseModel\n\nclass Report(BaseModel):\n    __tablename__ = 'reports'\n    scan_id = Column(Integer, ForeignKey('scans.id'), nullable=False)\n    file_path = Column(String, nullable=False)\n    status = Column(String, nullable=False)\n    scan = relationship(\"Scan\", back_populates=\"report\")\n",
        "backend/app/models/audit.py": "from sqlalchemy import Column, Integer, String, ForeignKey\nfrom sqlalchemy.orm import relationship\nfrom .base import BaseModel\n\nclass AuditLog(BaseModel):\n    __tablename__ = 'audit_logs'\n    user_id = Column(Integer, ForeignKey('users.id'), nullable=True)\n    action = Column(String, nullable=False)\n    ip_address = Column(String, nullable=True)\n    details = Column(String, nullable=True)\n    user = relationship(\"User\", back_populates=\"audit_logs\")\n",
        "backend/app/models/embedding.py": "from sqlalchemy import Column, Integer, ForeignKey\nfrom pgvector.sqlalchemy import Vector\nfrom sqlalchemy.orm import relationship\nfrom .base import BaseModel\n\nclass Embedding(BaseModel):\n    __tablename__ = 'embeddings'\n    scan_id = Column(Integer, ForeignKey('scans.id'), nullable=False)\n    vector = Column(Vector(768), nullable=False) # 768-dimensional vector\n    scan = relationship(\"Scan\", back_populates=\"embedding\")\n",
        "backend/app/models/cybertip.py": "from sqlalchemy import Column, String\nfrom .base import BaseModel\n\nclass CyberTip(BaseModel):\n    __tablename__ = 'cyber_tips'\n    title = Column(String, nullable=False)\n    content = Column(String, nullable=False)\n    category = Column(String, nullable=False)\n",
        "backend/app/models/__init__.py": "from .base import Base, BaseModel\nfrom .user import User\nfrom .scan import Scan\nfrom .details import ThreatResult, Recommendation, OfficialWebsite, ThreatSource\nfrom .report import Report\nfrom .audit import AuditLog\nfrom .embedding import Embedding\nfrom .cybertip import CyberTip\n",
        "backend/app/database/session.py": "from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession\nfrom sqlalchemy.orm import sessionmaker\nfrom app.config.settings import settings\nfrom app.models.base import Base\n\nengine = create_async_engine(settings.DATABASE_URL, echo=(settings.ENVIRONMENT == 'development'))\n\nAsyncSessionLocal = sessionmaker(\n    bind=engine,\n    class_=AsyncSession,\n    expire_on_commit=False\n)\n\nasync def get_db():\n    async with AsyncSessionLocal() as session:\n        yield session\n"
    }

    for path, content in files.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

if __name__ == "__main__":
    create_files()
    print("Backend Phase 8 (Models) scaffolded.")
