import os

def create_files():
    files = {
        "backend/app/config/settings.py": "from pydantic_settings import BaseSettings\n\nclass Settings(BaseSettings):\n    PROJECT_NAME: str = \"TrustGuardAI Enterprise API\"\n    VERSION: str = \"1.0.0\"\n    API_V1_STR: str = \"/api\"\n    SECRET_KEY: str = \"supersecretkey\"\n    ALGORITHM: str = \"HS256\"\n    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30\n    DATABASE_URL: str = \"postgresql+asyncpg://postgres:postgres@db:5432/trustguard\"\n    ENVIRONMENT: str = \"development\"\n    RATE_LIMIT_PER_MINUTE: int = 60\n\n    class Config:\n        env_file = \".env\"\n\nsettings = Settings()\n",
        "backend/app/logging/logger.py": "import logging\nimport sys\n\ndef setup_logging():\n    logger = logging.getLogger(\"trustguard\")\n    logger.setLevel(logging.INFO)\n    handler = logging.StreamHandler(sys.stdout)\n    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')\n    handler.setFormatter(formatter)\n    logger.addHandler(handler)\n    return logger\n\nlogger = setup_logging()\n",
        "backend/app/exceptions/custom.py": "class DomainException(Exception):\n    def __init__(self, message: str, status_code: int = 400, code: str = \"BAD_REQUEST\"):\n        self.message = message\n        self.status_code = status_code\n        self.code = code\n\nclass NotFoundException(DomainException):\n    def __init__(self, message: str = \"Resource not found\"):\n        super().__init__(message, status_code=404, code=\"NOT_FOUND\")\n\nclass UnauthorizedException(DomainException):\n    def __init__(self, message: str = \"Unauthorized\"):\n        super().__init__(message, status_code=401, code=\"UNAUTHORIZED\")\n",
        "backend/app/exceptions/handlers.py": "from fastapi import Request\nfrom fastapi.responses import JSONResponse\nfrom .custom import DomainException\nfrom app.logging.logger import logger\n\nasync def domain_exception_handler(request: Request, exc: DomainException):\n    logger.warning(f\"Domain Error: {exc.code} - {exc.message}\")\n    return JSONResponse(\n        status_code=exc.status_code,\n        content={\"error\": exc.message, \"code\": exc.code}\n    )\n\nasync def general_exception_handler(request: Request, exc: Exception):\n    logger.error(f\"Unhandled Error: {str(exc)}\")\n    return JSONResponse(\n        status_code=500,\n        content={\"error\": \"Internal server error\", \"code\": \"INTERNAL_ERROR\"}\n    )\n",
        "backend/app/database/session.py": "from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession\nfrom sqlalchemy.orm import sessionmaker, declarative_base\nfrom app.config.settings import settings\n\nengine = create_async_engine(settings.DATABASE_URL, echo=(settings.ENVIRONMENT == 'development'))\n\nAsyncSessionLocal = sessionmaker(\n    bind=engine,\n    class_=AsyncSession,\n    expire_on_commit=False\n)\n\nBase = declarative_base()\n\nasync def get_db():\n    async with AsyncSessionLocal() as session:\n        yield session\n",
        "backend/app/models/base.py": "from sqlalchemy import Column, Integer, DateTime\nfrom sqlalchemy.sql import func\nfrom app.database.session import Base\n\nclass BaseModel(Base):\n    __abstract__ = True\n    id = Column(Integer, primary_key=True, index=True)\n    created_at = Column(DateTime(timezone=True), server_default=func.now())\n    updated_at = Column(DateTime(timezone=True), onupdate=func.now())\n",
        "backend/app/models/user.py": "from sqlalchemy import Column, String, Boolean\nfrom .base import BaseModel\n\nclass User(BaseModel):\n    __tablename__ = 'users'\n    email = Column(String, unique=True, index=True, nullable=False)\n    hashed_password = Column(String, nullable=False)\n    is_active = Column(Boolean, default=True)\n    role = Column(String, default=\"user\")\n",
        "backend/app/models/scan.py": "from sqlalchemy import Column, Integer, String, Float, ForeignKey\nfrom .base import BaseModel\n\nclass Scan(BaseModel):\n    __tablename__ = 'scans'\n    user_id = Column(Integer, ForeignKey('users.id'), nullable=True)\n    target = Column(String, nullable=False)\n    scan_type = Column(String, nullable=False) # 'URL' or 'QR'\n    status = Column(String, default='pending')\n    risk_score = Column(Float, nullable=True)\n",
        "backend/app/schemas/user.py": "from pydantic import BaseModel, EmailStr\nfrom typing import Optional\nfrom datetime import datetime\n\nclass UserBase(BaseModel):\n    email: EmailStr\n\nclass UserCreate(UserBase):\n    password: str\n\nclass UserLogin(UserBase):\n    password: str\n\nclass UserResponse(UserBase):\n    id: int\n    is_active: bool\n    role: str\n    created_at: datetime\n    class Config:\n        from_attributes = True\n",
        "backend/app/schemas/scan.py": "from pydantic import BaseModel, HttpUrl\nfrom typing import Optional\nfrom datetime import datetime\n\nclass URLScanRequest(BaseModel):\n    target_url: HttpUrl\n\nclass QRScanRequest(BaseModel):\n    qr_data: str\n\nclass ScanResponse(BaseModel):\n    id: int\n    target: str\n    scan_type: str\n    status: str\n    risk_score: Optional[float]\n    created_at: datetime\n    class Config:\n        from_attributes = True\n",
        "backend/app/security/hashing.py": "from passlib.context import CryptContext\n\npwd_context = CryptContext(schemes=[\"bcrypt\"], deprecated=\"auto\")\n\ndef verify_password(plain_password: str, hashed_password: str) -> bool:\n    return pwd_context.verify(plain_password, hashed_password)\n\ndef get_password_hash(password: str) -> str:\n    return pwd_context.hash(password)\n",
        "backend/app/security/jwt.py": "from jose import jwt, JWTError\nfrom datetime import datetime, timedelta\nfrom app.config.settings import settings\nfrom app.exceptions.custom import UnauthorizedException\n\ndef create_access_token(data: dict) -> str:\n    to_encode = data.copy()\n    expire = datetime.utcnow() + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)\n    to_encode.update({\"exp\": expire})\n    return jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)\n\ndef decode_access_token(token: str) -> dict:\n    try:\n        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])\n        return payload\n    except JWTError:\n        raise UnauthorizedException(\"Invalid or expired token\")\n",
        "backend/app/middleware/security.py": "from fastapi import Request\nfrom starlette.middleware.base import BaseHTTPMiddleware\n\nclass SecurityHeadersMiddleware(BaseHTTPMiddleware):\n    async def dispatch(self, request: Request, call_next):\n        response = await call_next(request)\n        response.headers[\"Strict-Transport-Security\"] = \"max-age=31536000; includeSubDomains\"\n        response.headers[\"X-Content-Type-Options\"] = \"nosniff\"\n        response.headers[\"X-Frame-Options\"] = \"DENY\"\n        response.headers[\"X-XSS-Protection\"] = \"1; mode=block\"\n        return response\n",
        "backend/app/middleware/rate_limit.py": "from fastapi import Request, HTTPException\nfrom starlette.middleware.base import BaseHTTPMiddleware\nimport time\nfrom app.config.settings import settings\n\n# Simple in-memory rate limiter for demonstration\nIP_REQUESTS = {}\n\nclass RateLimitMiddleware(BaseHTTPMiddleware):\n    async def dispatch(self, request: Request, call_next):\n        client_ip = request.client.host\n        now = time.time()\n        \n        if client_ip not in IP_REQUESTS:\n            IP_REQUESTS[client_ip] = []\n            \n        # Clean up old requests\n        IP_REQUESTS[client_ip] = [req_time for req_time in IP_REQUESTS[client_ip] if now - req_time < 60]\n        \n        if len(IP_REQUESTS[client_ip]) >= settings.RATE_LIMIT_PER_MINUTE:\n            return JSONResponse(status_code=429, content={\"error\": \"Too many requests\", \"code\": \"RATE_LIMIT_EXCEEDED\"})\n            \n        IP_REQUESTS[client_ip].append(now)\n        return await call_next(request)\n"
    }

    for path, content in files.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

if __name__ == "__main__":
    create_files()
    print("Backend Phase 7 (Part 1) scaffolded.")
